apiVersion: k3s.cattle.io/v1
kind: HelmChart
metadata:
  name: istio-main
  namespace: kube-system
spec:
  chart: https://%{KUBERNETES_API}%/static/charts/istio.tgz
  targetNamespace: istio-system
  valuesContent: |-
    grafana:
      enabled: true
    tracing:
      enabled: true
    kiali:
      enabled: true
      dashboard:
        jaegerURL: http://jaeger-query:16686
        grafanaURL: http://grafana:3000
